### ISSUE TITLE
Health Check - trusted application - python error

### ISSUE THREAD

**Issue by dkrotil** [tdharris/dsapp#52]
Build 203

Running Health Check i´m getting this error 

Verifying Trusted Application...
Traceback (most recent call last):
  File "./mobility/cli/gw_login.py", line 23, in <module>
  File "/opt/novell/datasync/common/lib/suds/client.py", line 540, in __call__
    return client.invoke(args, kwargs)
  File "/opt/novell/datasync/common/lib/suds/client.py", line 600, in invoke
    result = self.send(soapenv)
  File "/opt/novell/datasync/common/lib/suds/client.py", line 635, in send
    reply = transport.send(request)
  File "/opt/novell/datasync/common/lib/suds/transport/https.py", line 64, in send
    return  HttpTransport.send(self, request)
  File "/opt/novell/datasync/common/lib/suds/transport/http.py", line 77, in send
    fp = self.u2open(u2request)
  File "/opt/novell/datasync/common/lib/suds/transport/http.py", line 118, in u2open
    return url.open(u2request, timeout=tm)
  File "/usr/lib64/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 1186, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.6/urllib2.py", line 1161, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -5] No address associated with hostname>

**Comment by snielson** [comment]
Can you attach your /etc/datasync/configengine/engines/default/pipelines/pipeline1/connectors/groupwise/connector.xml 

Or email it to snielson@novell.com

**Comment by snielson** [comment]
When grabbing the gListenAddress variable (Groupwise server address). We were only searching for numbers as a IP. Fixed our search to grab the entire value, regardless of characters.

IP address, and hostnames should now work fine.

I've also added some extra statements to catch more errors, and give a better reason for the warning or fail in the healthcheck log.

Fixed checked in v206
